name: Build Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  PROJECT_VERSION: "1.0.0"

jobs:
  build:
    name: Build and Cache Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Before Checkout
        run: ls
    
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: After Checkout
        run: ls
        
      - name: Project Version
        run: echo $PROJECT_VERSION
        
      - name: Setup Java JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Cache
        uses: actions/cache@v4.1.2
        with:
          path: ${{ github.workspace }}/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles("**/pom.xml") }}

      - name: Create JAR
        run: mvn clean package -DskipTests -Djar.finalName=helloworld-$PROJECT_VERSION
        env:
          MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/.m2/repository"
